"""
Project Builder — scaffolds new projects
Version: 1.0.0
"""

from pathlib import Path
from typing import Any, Dict


class ProjectBuilder:
    """Scaffolds new projects with AI-Brain-Framework structure."""

    DEFAULT_STRUCTURE = {
        "src": {"__init__.py": ""},
        "tests": {"__init__.py": ""},
        "docs": {},
        "README.md": "# {name}\n\nGenerated by AI-Brain-Framework.\n",
        ".gitignore": "__pycache__/\n*.pyc\n.env\n",
        "pyproject.toml": "[project]\nname = \"{name}\"\nversion = \"0.1.0\"\n",
    }

    def build(self, name: str, target: str = ".") -> Dict[str, Any]:
        root = Path(target) / name
        files_created = []

        def create(spec: Dict[str, Any], base: Path):
            for key, value in spec.items():
                if key.endswith(".py") or key.endswith(".md") or key.endswith(".toml") or key.endswith(".gitignore"):
                    if isinstance(value, str):
                        content = value.format(name=name)
                        path = base / key
                        path.parent.mkdir(parents=True, exist_ok=True)
                        path.write_text(content, encoding="utf-8")
                        files_created.append(str(path))
                elif isinstance(value, dict):
                    (base / key).mkdir(parents=True, exist_ok=True)
                    files_created.append(str(base / key))
                    create(value, base / key)

        root.mkdir(parents=True, exist_ok=True)
        create(self.DEFAULT_STRUCTURE, root)

        return {
            "project": name,
            "path": str(root),
            "files_created": len(files_created),
            "items": files_created,
        }
